#include <math.h>
#include <stdio.h>
#include <string.h>
#include <iostream>
#include <list>

#include "individu.h"
#include "population.h"
#include "ag.h"
#include "random.h"

using namespace std;

int Data::demi_journee[11] = {0};
int Data::retrier[NBR_FORMATIONS] = {0};

/* competences des interfaces en SIGNES et CODAGE*/
int Data::competences_interfaces[NBR_INTERFACES_TOTAL][2]={
	{1,0},
	{0,1},
	{0,1},
	{1,0},
	{0,1},
	{1,0},
	{1,0},
	{1,0},
	{0,1},
	{0,1},
	{1,1},
	{1,1},
	{0,1},
	{1,1},
	{1,1},
	{1,1}
};

/* specialite des interfaces */
int Data::specialite_interfaces[NBR_INTERFACES_TOTAL][NBR_SPECIALITES]={
	{1,0,0,0,0},
	{0,0,0,1,0},
	{0,0,1,0,0},
	{0,0,0,0,1},
	{0,1,0,0,0},
	{1,0,0,0,0},
	{0,1,0,0,0},
	{0,0,1,0,0},
	{0,0,0,1,0},
	{0,0,0,1,1},
	{0,0,1,1,0},
	{1,0,0,0,0},
	{0,1,0,0,0},
	{0,0,0,1,0},
	{0,0,1,0,0},
	{0,1,0,0,0}
};

/* coordonnées des centres de formation, des interfaces et des apprenants */
float Data::coord[NBR_NODES][2]={

	/* Les interfaces se rendent du centre SESSAD à l'école de formation */
	{0,46}, /* centre 0 */
	/* Centres de formation */
	{62,30}, /* ecole formation SPECIALITE_MENUISERIE */
	{128,105}, /* ecole formation SPECIALITE_ELECTRICITE */
	{68,86}, /* ecole formation SPECIALITE_MECANIQUE */
	{174,10}, /* ecole formation SPECIALITE_INFORMATIQUE */
	{165,17} /* ecole formation SPECIALITE_CUISINE */
};

// Le planning
int Data::formation[NBR_FORMATIONS_TOTAL][6]={
	{0,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MARDI,14,17},
	{1,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,9,11},
	{2,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,14,18},
	{3,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,9,11},
	{4,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,15,18},
	{5,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,JEUDI,14,18},
	{6,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MERCREDI,16,19},
	{7,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,14,18},
	{8,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,10,12},
	{9,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,LUNDI,10,12},
	{10,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,8,10},
	{11,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,9,12},
	{12,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,16,19},
	{13,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,13,19},
	{14,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MERCREDI,16,19},
	{15,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,13,19},
	{16,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,16,19},
	{17,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,13,19},
	{18,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,15,17},
	{19,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,13,15},
	{20,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,VENDREDI,10,12},
	{21,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,15,18},
	{22,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,16,18},
	{23,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,13,18},
	{24,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,16,19},
	{25,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,16,19},
	{26,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,10,12},
	{27,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,LUNDI,16,19},
	{28,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MARDI,15,19},
	{29,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,13,16},
	{30,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,14,19},
	{31,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,9,11},
	{32,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,JEUDI,10,12},
	{33,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,8,11},
	{34,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,10,12},
	{35,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,14,18},
	{36,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,10,12},
	{37,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,16,18},
	{38,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,8,12},
	{39,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,8,12},
	{40,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,9,11},
	{41,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MERCREDI,10,12},
	{42,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,9,11},
	{43,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,SAMEDI,9,11},
	{44,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,8,10},
	{45,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,LUNDI,13,15},
	{46,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,10,12},
	{47,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,10,12},
	{48,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,10,12},
	{49,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,15,18},
	{50,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,14,19},
	{51,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,15,17},
	{52,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MARDI,10,12},
	{53,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,LUNDI,8,10},
	{54,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,8,12},
	{55,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,14,19},
	{56,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,9,11},
	{57,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,10,12},
	{58,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MARDI,10,12},
	{59,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,14,17},
	{60,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,9,11},
	{61,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,16,18},
	{62,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,14,19},
	{63,SPECIALITE_CUISINE,COMPETENCE_CODAGE,LUNDI,10,12},
	{64,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,9,11},
	{65,SPECIALITE_CUISINE,COMPETENCE_SIGNES,LUNDI,16,19},
	{66,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,10,12},
	{67,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,13,15},
	{68,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,SAMEDI,15,18},
	{69,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,13,18},
	{70,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,10,12},
	{71,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,VENDREDI,13,17},
	{72,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,8,10},
	{73,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,16,18},
	{74,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,15,18},
	{75,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,SAMEDI,10,12},
	{76,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,10,12},
	{77,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,15,17},
	{78,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,JEUDI,8,11},
	{79,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,JEUDI,8,11}
};

int main(int argc, char **argv)
	// argc : nombre de parametres
	// argv : tableau contenant les parametres
	// Soit l'executable 'algo_evo' ne prend pas d'arguments soit il prend 6 arguments :
	// 1. nombre de génération (entier > 0)
	// 2. taille de la population (entier > 0)
	// 3. taux de croisement (0 <= reel <= 1)
	// 4. taux de mutation (0 <= reel <= 1)
	// 5. nombre de villes (=taille d'un chromosome)
	// 6. nom du fichier indiquant les distances entre villes
{
	// initialise le générateur de nombre aléatoire
	Random::randomize();
	Data::tri_formations();
	cout<<"Demarrage de l'algorithme"<<endl;

	int duree     = 2000;
	int taille_population = 1000;
	float taux_croisement = 0.002;
	float taux_mutation   = 0.01;
	int taille_individu = NBR_FORMATIONS;
	// initialise l'algorithme évolutionniste
	Ag algo(duree, taille_population, taux_croisement, taux_mutation, taille_individu);

	individu *best = algo.optimiser();
	// affiche la fitness du meilleur individu trouvé
	cout << "La meilleure solution trouvee est : ";
	best->afficher();

}


